pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/manassonu/Jenkins-Zero-To-Hero.git', branch: 'main'
            }
        }

        stage('Build & Test') {
            agent { docker { image 'node:16-alpine' } }
            steps {
                sh '''
                  # adjust path if package.json is in a subfolder
                  if [ -f package.json ]; then
                    npm install
                    npm test
                  else
                    echo "No package.json found, skipping npm install"
                  fi
                '''
            }
        }

        stage('Deploy') {
            agent { docker { image 'bitnami/kubectl:latest' } }
            steps {
                sh 'kubectl apply -f deployment.yml'
            }
        }
    }
}
