pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
    stage('Dev') {
  agent {
    docker {
      image 'lachlanevenson/k8s-kubectl:v1.27.3'
    }
  }
  steps {
    sh 'kubectl apply -f deployment.yml'
  }
}
  }
}
