pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/manassonu/Jenkins-Zero-To-Hero.git', branch: 'main'
            }
        }

        stage('Build & Test') {
            agent {
                docker {
                    image 'node:16-alpine'
                }
            }
            steps {
                sh 'node --version'
                sh 'npm install'
                sh 'npm test'
            }
        }

        stage('Deploy') {
            agent {
                docker {
                    image 'bitnami/kubectl:latest'
                }
            }
            steps {
                sh 'kubectl apply -f deployment.yml'
            }
        }
    }
}
